### ISSUE TITLE
Build process?

### ISSUE THREAD

**Issue by davelab6** [erinmclaughlin/Hubli#1]
How are you actually building the UFO into binaries atm?

**Comment by erinmclaughlin** [comment]
I work within the "Wire" file, then expand it using Outliner tool, save the new .ufo as "Expanded", and then create an .otf or .ttf from it using RoboFont's default Generate Font tool.

**Comment by davelab6** [comment]
Okay cool :) no worries

**Comment by davelab6** [comment]
@neelakash and @naorem are working on a couple of Bengali projects, 

https://github.com/brandnewtype/hoogli 

https://github.com/brandnewtype/ektana

They would like to use your Hubballi Latin in Hoogli, but as it is a family of weights, they'd a little more documentation about how you turned 

UFO/DEV%20UFOS/Hubballi-Regular-wire.ufo

into 

UFO/Hubballi-Regular.ufo
- which Outliner settings did you use
- what kind of post-outliner modifications did you make
- in the project's [google-fonts-discuss thread](https://groups.google.com/forum/#!searchin/googlefonts-discuss/hubballi/googlefonts-discuss/zZfY-35xJ3o/_c3ONaxhAgAJ) you mentioned in the thread you came up with a good overshoot strategy - what was it? :) 

If you could add these to `README.md` or `documentation/README.md` that would be ideal :)

**Comment by erinmclaughlin** [comment]
Yes, I'll definitely put that info together for them. I think all four of us should have a discussion about the eventual weights, as I'd also like to expand the Hubballi thing to other weights and scripts and would like to have a say in it! :)

**Comment by davelab6** [comment]
Would you all be able to make a call at 10am NYC time on Thursday?

**Comment by erinmclaughlin** [comment]
Sure!

**Comment by naorem** [comment]
Confirming the video call on Thursday 17 March, 10 am NYC time (8:30 pm New
Delhi Time).
- 9 1\* 9 8 7 3 1 1 0 4 6 3*
- 9 1\* 9 7 1 7 7 9 4 8 0 5*

S-102, Ground Floor
Pancheel Park, New Delhi 110017

   http://www.naorem.com

http://www.twitter.com/AndyNaorem http://www.linkedin.com/in/naorem

**Comment by davelab6** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYey8CYirbA4KcxM2MfVCb8sKA8Tc94LZYK85dLPM_KhvhCjUQ?hl=en-GB&authuser=0
