### ISSUE TITLE
subscript spacing issue

### ISSUE THREAD

**Issue by erinmclaughlin** [erinmclaughlin/Hubli#9]
Hi, @schriftgestalt and @davelab6 !
Now that this project has been re-built using Glyphs, the virama (halant) issue is fixed, but another problem has arisen.

Kerning between the subscripts is no longer working as expected. I imagine this must be related to the way the program is dealing with the virama issue. Here's an example: https://github.com/erinmclaughlin/Hubballi/blob/master/source/kannada_two_subscript_example.png

I've double-checked the kerning and subscript sidebearings used in some of these differing combinations, and the values are the same in both files: https://github.com/erinmclaughlin/Hubballi/blob/master/source/metricsmachine_comparison.png

Georg, do you have any idea if it's possible to fix this?

Thanks!

Erin

File info, in case you need it:

-- https://github.com/erinmclaughlin/Hubballi/tree/master/source/development%20ufos/Hubballi-Regular-Glyphs-export.ufo  This is the .ufo that I was using in MetricsMachine to re-build and double-check kerning in. I used the "Import Metrics" option in Glyphs to transfer this file's kerning info into to the master Glyphs file, https://github.com/erinmclaughlin/Hubballi/blob/master/source/Hubballi-Regular.glyphs

-- https://github.com/erinmclaughlin/Hubballi/tree/master/source/development%20ufos/Hubballi-Regular-Robofontmu.ufo  This is the old Robofont-created .ufo that I am using as a baseline for my comparisons, as it worked correctly.

-- https://github.com/erinmclaughlin/Hubballi/tree/master/source/generated%20test%20fonts  The fonts I used in the Impallari test page are here.

**Comment by schriftgestalt** [comment]
The problem is that the kern/dist feature for all indic scripts have the lookupflag 'IgnoreMarks' set. That allows kerning between base glyphs even if there are marks in between. But breaks kerning between marks, too. I disabled it for kannada for now and will improve the kern feature generator to allow both.

**Comment by davelab6** [comment]
cc @DunwichType

**Comment by schriftgestalt** [comment]
Can you test this font?
[Hubballi-Regular.otf.zip](https://github.com/erinmclaughlin/Hubballi/files/242468/Hubballi-Regular.otf.zip)

**Comment by erinmclaughlin** [comment]
@schriftgestalt Oh wow, that works perfectly. Thank you! What should I do next to make sure this is implemented in my project files? Is this just an update to Glyphs itself that you've written?

THANK YOU SO MUCH, I can't believe how responsive you are on all of these issues. I'm so grateful.
